name: backend_supabase
description: Supabase backend implementation for eipat.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  backend_core:
    path: ../backend_core
  supabase_flutter: ^2.10.4
